### ISSUE TITLE
Confusion in the about-text

### ISSUE THREAD

**Issue by semiversus** [gaudiatech/kengi#28]
In the Github About text the first sentence is "cool game engine written in Python<3," which led me to not further investigate into this project, as it is only supporting Python 2 (or even 1?)...

If you want to use a heart symbol you can add it as unicode character like this: ❤️

**Comment by wkta** [comment]
You're 100% right,
it would be better to use a unicode character. Te error has been fixed, thank you!

The game engine "pyved-engine" is indeed a **modern project** and is compatible with any 3.x version of the python interpreter.

 Feel free to investigate the project. A good place to start is by taking a look at the video tutorial. Then you may take a look at the written tutorial:

- https://www.youtube.com/watch?v=CV3flP6i6Ec
- https://gaudiatech.github.io/pyved-engine/
