### ISSUE TITLE
requests error

### ISSUE THREAD

**Issue by wkta** [gaudiatech/kengi#4]
when katasdk is used "on thonny"
it seems to raise an error related to the `requests` package

![requests-err](https://user-images.githubusercontent.com/4610125/135989879-56498bb7-2a96-4233-bf02-221d6a163102.png)

**Comment by Kyuchumimo** [comment]
Thonny is an Python (Python 3.7 in this case) integrated development environment (IDE). See: https://thonny.org/
The error when exporting to webtest occurs after installing katasdk in Thonny plug-ins.

To make it work again, you have to reinstall katasdk with `pip install katasdk --force-reinstall`

**Comment by Kyuchumimo** [comment]
error reproduction:
https://user-images.githubusercontent.com/74131798/136078826-d07685a3-6c47-4904-a7af-c03780723427.mp4

**Comment by Kyuchumimo** [comment]
error reproduction:
https://user-images.githubusercontent.com/74131798/136081208-8d7f2878-612f-42c7-9711-0fe15d24308e.mp4

**Comment by wkta** [comment]
Thank you very much for pointing out the bug and letting me know about _users who like to use the Thonny IDE._

I 'll analyze this again (after the very long wait) as a new version of the game engine will be released soon.
Right now:

- I am testing the tool along with Thonny 4.1.4.
- installing the package (new name: `pyved_engine`) works fine
- you can also initialize a new game by using the `pyv-cli init myBundle` command, after clicking `Tools -> Open system shell` in the IDE
- if one opens `launch_game.py` and Execute that launcher script, everything works as intended, the game runs properly

But a new variant of the problem apeears when trying to share the web version of your game…
(Example below)
![image](https://github.com/gaudiatech/pyved-engine/assets/4610125/4ca0e805-4417-4615-a4f5-5233a26d8475)

We will fix that bug very soon.

**Comment by wkta** [comment]
Works fine in version `24.9a1` ! 👍

When installing `pyved-engine` (the old `katasdk` library is superseded by the standalone engine)

To test all features within Thonny:
- first install the modern package using `Tools>Manage packages`
- use `Tools > Open System shell` 
- use the `pyv-cli` tool as explained in tutorials

Within Thonny you can open the `launch_game.py` file and other files in `cartridge/*.py` and run the main file (`launch_game.py`) if you wish to analyze the code by yourself
